mkdir 1keystore              
mkdir poster-data-c           
mkdir seqdata_c
mkdir config
mkdir postgres-data           
mkdir seqdata_d
mkdir consensus               
mkdir poster-data             
mkdir seqdata                 
mkdir unsafestaker-data
mkdir l1data                  
mkdir poster-data-b           
mkdir seqdata_b               
mkdir validator-data
mkdir sdk-data
touch ./sdk-data/localNetwork.json